version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: phpmyadminpassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  node:
    build: .
    container_name: my-node-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    networks:
      - app-network

  

networks:
  app-network:
    driver: bridge
